services:

  postgres:
    image: postgres:16
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:  
      context: ./backend
      dockerfile: ../infra/docker/backend.Dockerfile

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    volumes:
      - ./backend:/app   # useful for dev (hot reload)
    
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    restart: unless-stopped
    
    env_file:
      - .env.backend
  frontend:
    build:
      context: ./frontend/Project_Intelligence_Frontend
      dockerfile: ../../infra/docker/frontend.Dockerfile

    container_name: frontend

    ports:
      - "5173:5173"

    environment:
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./frontend/Project_Intelligence_Frontend:/app
      - /app/node_modules

    command: npm run dev -- --host 0.0.0.0

    depends_on:
      - backend

    restart: unless-stopped

volumes:
  postgres_data: